### ISSUE TITLE
Module Structure

### ISSUE THREAD

**Issue by VivianWilde** [PoliticalComputerScience/PCS-Website#3]
Decide on a module structure for the code going forward.

## Tentative thoughts:
- `components` and `pages` directories
- `data` directory : Contains stuff like a list of club members as JSON which we can pull from to generate pages
- `api` or `lib` or `utils`: Contains code utilities (not visual components), for things like processing JSON, routing, and other stuff that comes up. 
- `assets` or `static`, to hold images and other resources
- One open question now is organisation within the components directory. 
- For instance, do we want to have `components/<page>` folders to store components tightly coupled with a specific page?
- Note: The site is mostly going to be static and non-interactive, so we don't need to devote too much worry to the `api`, etc. code folders.

**Comment by na933950** [comment]
Yup I agree with a lot of this-- particularly `components` and `pages`

I think the `data` directory should be in `public` rather than `src` because it is static data.

`utils` can be in the `src` folder and contain (probably for the front end at least) constants which will be the text that appears on our page, and helper functions if need be.

I think generally components can be all in the components folder and comments can be left in each file to say which page they're for anyway. In my opinion, to maintain solid structures and styles for our web app, it might be better even to make the components folder page-independent and further break it down into `/buttons`, `forms`, `layout` (navbar, footer, etc.),
